### ISSUE TITLE
It doesn't work on Windows XP

### ISSUE THREAD

**Issue by xezpeleta** [puodzius/Check-EternalBlue#1]
Hi!

The script works great on Windows 2008r2, Windows 10 etc... Unfortunately, it doesn't work on Windows XP:

```
Line: 6
Char: 1
Error: ActiveX component can't create object 'System.Collections.ArrayList'
```

Is it possible to make it compatible with Windows XP?

Thanks!

**Comment by cpuodzius** [comment]
Hi @xezpeleta ,

The script depends on a .NET component, which is not present by default on WinXP.

ESET just released a [tool](https://help.eset.com/eset_tools/ESETEternalBlueChecker.exe) that works on WinXP too.  Please check it out.
